# Window환경에서 mysql volume을 설정하려면 권한 문제 해결해야함
# linux 환경에선 volume 설정해도 문제없이 돌아감

version: '3.8'

services:
  batch:
    image: batch
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    depends_on:
      - mysql1
      - mysql2
    restart:
      always
    networks:
      - dbnet

  mysql1:
    image: mysql:8.0
    container_name: mysql1
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: default
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql1/:/var/lib/mysql
    networks:
      - dbnet

  mysql2:
    image: mysql:8.0
    container_name: mysql2
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: batch
    ports:
      - "3307:3306"
    volumes:
      - ./data/mysql2/:/var/lib/mysql
    networks:
      - dbnet

networks:
  dbnet:
    driver: bridge